[project]
name = "mna"
version = "0.1.0"
description = "A sophisticated M&A automation system"
authors = ["Adept (ATS) Inc. <yourmail@email.com"]
readme = "README.md"
dependencies = [
    "crewai[tools]>=0.85.0",
]
requires-python = ">=3.11"